name: Publish to Maven Central

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 8 and Maven Central
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Import Base64 GPG Key
        run: |
           echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 -d | gpg --batch --import

      - name: Build and Sign (No Deploy)
        run: mvn clean verify -P release -DskipTests -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}

      - name: Create Deployment Bundle
        run: |
          mkdir deployment-bundle
          cp target/*.jar target/*.pom target/*.asc deployment-bundle/
          # Remove Exec jar if exists as it's not for central
          rm -f deployment-bundle/*-exec.jar
          cd deployment-bundle
          zip -r ../bundle.zip .

      - name: Upload Bundle to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: maven-central-bundle
          path: bundle.zip
